#NOTE BELOW IS FOR DEMONSTRATION PURPOSES ONLY
name: Continuous Integration

on:
  push:
    branches:
      - main
#Comment out below since build will not complete due to missing secrets and artifacts
  #pull_request:
  #  branches:
  #    - main
  
env:
  DOCKER_IMAGE_NAME: chuck-norris
  IMAGE_REGISTRY_URL: docker.pkg.github.com

jobs:
  build_and_publish_artifacts:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ github.sha }}
          build-args: |
            ${{steps.version_step.outputs.version}}